title:
email:
description:
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.localtshirt.com/" # the base hostname & protocol for your site
twitter_username:
github_username:
paginate: 20
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown
plugins: [jekyll-paginate]


sass:
  sass_dir: assets/css
  style: :nested

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      author:
      layout: "post"
